# Generated by Django 3.2.8 on 2021-10-10 08:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookedSlot',
            new_name='BookSlot',
        ),
    ]
